### ISSUE TITLE
DChat to ChatChat convertor breaks completely

### ISSUE THREAD

**Issue by BlitzOffline** [HelpChat/toolbox#16]
Whenever I add a DeluxeChat format without the tooltips, the entire page just breaks and a refreshe is needed.

example config:

```
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '&7[%vault_group%&7] '
    name_color: '&b'
    name: '%player_name%'
    suffix: '&7> '
    chat_color: '&f'
```

When it breaks it tells me to check the console https://i.imgur.com/dEc9EKv.png
This is what I find in console https://i.imgur.com/1p3PVL3.png
