### ISSUE TITLE
ChatChat format has changed.

### ISSUE THREAD

**Issue by BlitzOffline** [HelpChat/toolbox#18]
The ChatChat format has been changed. It currently looks like this:
```
formats:
  format-name:
    priority: # 
    parts:
      part-name:
      - ''
      - ''
      other-part-name:
      - ''
```

It can have infinite parts.
